name: Run tests
on:
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'
  push:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - run: java --version
      - run: mvn -v
      - name: Build with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: mvn clean install -s .github/workflows/settings.xml