name: push-on-branch

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'

jobs:
  call-reusable:
    uses: bettor-league/reusable-workflow/.github/workflows/java-maven-ci.yml@master
    secrets:
      maven-settings: ${{ secrets.MAVEN_SETTINGS }}