name: Run tests
on:
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'
  push:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: '17.0'
      - run: java --version
      - run: mvn -v
      - name: Build with Maven
        run: mvn --settings .github/workflows/settings.xml clean install