name: push-on-branch

on:
  push:
    branches:
      - '*'
      - '!master'
      - '!gh-pages'

jobs:
  build-sdk:
    uses: bettor-league/reusable-workflow/.github/workflows/java-project.yml@master
    with:
      maven_command: 'clean install'
    secrets: inherit