name: push-on-branch

on:
  push:
    branches:
      - '*'
      - '!master.yml'
      - '!gh-pages'

jobs:
  call-reusable:
    uses: bettor-league/reusable-workflow/.github/workflows/java-maven-ci.yml@master.yml
    secrets:
      github-token: ${{ secrets.TOKEN }}